# Generated by Django 5.2.8 on 2025-11-14 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_usuario_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_hab', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('actividad_cargo', models.CharField(max_length=120)),
                ('fecha_hora', models.DateTimeField()),
                ('pago', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=20)),
                ('empleador', models.ForeignKey(limit_choices_to={'rol': 'empleador'}, on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_req', models.CharField(max_length=255)),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.trabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=20)),
                ('contacto', models.CharField(max_length=50)),
                ('trabajador', models.ForeignKey(limit_choices_to={'rol': 'trabajador'}, on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.trabajo')),
            ],
        ),
    ]
