# Generated by Django 5.2.8 on 2025-11-21 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='title',
        ),
    ]
