# Generated by Django 5.2.8 on 2025-11-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('COMPANY', 'Empresa'), ('USER', 'Usuario')], default='USER', max_length=20),
        ),
    ]
